nname: Schedule Job

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Schedule Workflow Execute"

 steps:
 - name: Print Message
 run: echo "Schedule Workflow Exceute"
 
